---
version: '3.7'
services:
  maven:
    build: 
      context: build/
    volumes:
      - /tmp:/tmp/boxfuse-sample-java
      
  tomcat:
    build: 
      context: prod/
    volumes: 
      - /tmp:/tmp/build
    ports:
      - 8080:8080
    depends_on: 
      - maven

volumes:
  maven:
  tomcat:      
