---
version: '3.7'
services:
  maven:
    build: 
      context: build/
    volumes:
      - type: volume
        source: artifacts
        target: /tmp/boxfuse-sample-java/target/
      
  tomcat:
    build: 
      context: prod/
    volumes: 
      - type: volume
        source: artifacts
        target: /usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on: 
      - maven

volumes:
  artifacts:      