---
version: '3.7'
services:
  maven:
    build: 
      context: build/
    volumes:
      - type: volume
        source: artifacts
        target: /tmp/art
      
  tomcat:
    image: tomcat:9.0.71-jdk11-temurin-focal
    volumes: 
      - type: volume
        source: artifacts
        target: /usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on: 
      - maven

volumes:
  artifacts:      