---
version: '3.7'
services:
  maven:
    build: 
      context: build/
    volumes:
      - type: bind
        source: /tmp/build
        target: /tmp/boxfuse-sample-java/target
      
  tomcat:
    build: 
      context: prod/
    volumes: 
      - type: bind
        source: /tmp/build
        target: /usr/local/tomcat/webapp
    ports:
      - 8080:8080
    depends_on: 
      - maven

      
