---
version: '3.7'
services:
  maven:
    build: 
      context: build/
    volumes:
      - type: bind
        source: /tmp/build
        target: /tmp/boxfuse-sample-java
      
  tomcat:
    build: 
      context: prod/
    volumes: 
      - type: bind
        source: /tmp/build
        target: /tmp
    ports:
      - 8080:8080
    depends_on: 
      - maven

volumes:
  /tmp/build:
      
